[2025-03-23T04:40:21.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenar_modelo.entrenar_modelo_rf manual__2025-03-23T04:40:04.371867+00:00 [queued]>
[2025-03-23T04:40:21.851+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenar_modelo.entrenar_modelo_rf manual__2025-03-23T04:40:04.371867+00:00 [queued]>
[2025-03-23T04:40:21.855+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-03-23T04:40:21.962+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo_rf> on 2025-03-23 04:40:04.371867+00:00
[2025-03-23T04:40:22.092+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2025-03-23T04:40:22.171+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'entrenar_modelo', 'entrenar_modelo_rf', 'manual__2025-03-23T04:40:04.371867+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/entrenar_modelo.py', '--cfg-path', '/tmp/tmp6nwfb5at']
[2025-03-23T04:40:22.237+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask entrenar_modelo_rf
[2025-03-23T04:40:22.823+0000] {task_command.py:415} INFO - Running <TaskInstance: entrenar_modelo.entrenar_modelo_rf manual__2025-03-23T04:40:04.371867+00:00 [running]> on host 37b147adca64
[2025-03-23T04:40:23.806+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='entrenar_modelo' AIRFLOW_CTX_TASK_ID='entrenar_modelo_rf' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T04:40:04.371867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T04:40:04.371867+00:00'
[2025-03-23T04:40:33.745+0000] {logging_mixin.py:151} WARNING - 2025/03/23 04:40:33 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-03-23T04:41:39.443+0000] {logging_mixin.py:151} WARNING - 2025/03/23 04:41:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-03-23T04:41:41.102+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-03-23T04:41:52.825+0000] {logging_mixin.py:151} INFO - üèÉ View run shivering-mare-317 at: http://mlflow:5000/#/experiments/1/runs/dd5a3092d91c4cff84b99f8e04b488f6
[2025-03-23T04:41:52.834+0000] {logging_mixin.py:151} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-03-23T04:41:52.953+0000] {logging_mixin.py:151} INFO - Entrenamiento finalizado con accuracy: 1.0
[2025-03-23T04:41:52.999+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-23T04:41:53.213+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=entrenar_modelo, task_id=entrenar_modelo_rf, execution_date=20250323T044004, start_date=20250323T044021, end_date=20250323T044153
[2025-03-23T04:41:53.660+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-23T04:41:53.820+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
